{
 "title": "OYRON Inventory API Part 3 completed",
 "description": "Radix default dashboard for apps",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Radixapp",
    "query": {
     "query": "label_values(kube_namespace_labels,label_radix_app)"
    }
   },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values({namespace=~\"$Radixapp-.*\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace Ingress requests pr. min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests [1m])*60) by (exported_namespace, status) * on (exported_namespace) group_left(label_radix_app) (label_replace(kube_namespace_labels{namespace=~\"$Radixapp.*\"}, \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"))",
     "legendFormat": "{{exported_namespace}} - {{status}}"
    }
   ]
  },
  {
   "title": "Average Ingress requests duration (sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_sum [5m])) by (exported_namespace, status, method)/ sum(rate(nginx_ingress_controller_request_duration_seconds_count [5m])) by (exported_namespace, status, method)\n* on (exported_namespace) group_left(label_radix_app) (label_replace(kube_namespace_labels{namespace=~\"$Radixapp.*\"}, \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"))",
     "legendFormat": "{{exported_namespace}} - {{status}} - {{method}}"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(\n  irate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\", container!=\"\"}[5m])\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$Namespace\"}\n) by (workload, workload_type, namespace, pod)) * on (namespace) group_left(label_radix_app) kube_namespace_labels {namespace=~\"$Radixapp.*\"}",
     "legendFormat": "Utilise {{ namespace }} - {{ workload }} - {{ pod }}"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests {resource=\"cpu\"} * on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$Namespace\"}\n) by (workload, workload_type, namespace, pod)) * on (namespace) group_left(label_radix_app) kube_namespace_labels {namespace=~\"$Radixapp.*\"}",
     "legendFormat": "Requested {{ namespace }} - {{ workload }} - {{ pod }}"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(\n    container_memory_working_set_bytes{namespace=~\"$Namespace\", container!=\"\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$Namespace\"}\n) by (workload, workload_type, namespace, pod)) * on (namespace) group_left(label_radix_app) kube_namespace_labels {namespace=~\"$Radixapp.*\"}",
     "legendFormat": "Utilise {{namespace}} - {{workload}} - {{pod}}"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests {resource=\"memory\"} * on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$Namespace\"}\n) by (workload, workload_type, namespace, pod)) * on (namespace) group_left(label_radix_app) kube_namespace_labels {namespace=~\"$Radixapp.*\"}",
     "legendFormat": "Requested {{namespace}} - {{workload}} - {{pod}}"
    }
   ]
  },
  {
   "title": "CI Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(ceil(rate(radix_operator_radix_job_processed{application=\"$Radixapp\"}[2m]))) by (status)",
     "legendFormat": "{{status}} jobs"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase {phase=\"Running\", namespace=~\"$Namespace\"} * on (namespace) group_left(label_radix_app) kube_namespace_labels {namespace=~\"$Radixapp.*\"}) by (namespace)",
     "legendFormat": "Running pods in {{namespace}}"
    },
    {
     "expr": "sum(kube_pod_status_phase {phase=\"Pending\", namespace=~\"$Namespace\"} * on (namespace) group_left(label_radix_app) kube_namespace_labels {namespace=~\"$Radixapp.*\"}) by (namespace)",
     "legendFormat": "Pending pods in {{namespace}}"
    },
    {
     "expr": "sum(kube_pod_status_phase {phase=\"Failed\", namespace=~\"$Namespace\"} * on (namespace) group_left(label_radix_app) kube_namespace_labels {namespace=~\"$Radixapp.*\"}) by (namespace)",
     "legendFormat": "Failed pods in {{namespace}}"
    }
   ]
  }
 ]
}