{
 "title": "OYRON Inventory API rehearsal",
 "description": "Radix default dashboard for apps",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Radixapp",
    "query": {
     "query": "label_values(kube_namespace_labels,label_radix_app)"
    }
   },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values({namespace=~\"$Radixapp-.*\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 } },
  {
   "title": "Inventory size",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oyron_inventory_size" }
   ]
  },
  {
   "title": "Endpoint requests pr second [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, route) (rate(oyron_inventory_request_counter_total[1m]))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Requests pr minute [1m]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(label_replace(increase(oyron_inventory_request_counter_total[1m]), \"status\", \"2**\", \"status\", \"(2..)\")) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request duration [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(oyron_inventory_request_duration_sum[1m])/rate(oyron_inventory_request_duration_count[1m])",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Errors pr second [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(oyron_inventory_request_counter_total{status=~\"[45]..\"}[1m]))",
     "legendFormat": "{{method}} {{route}} {{status}}"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(\n  irate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\", container!=\"\"}[5m])\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$Namespace\"}\n) by (workload, workload_type, namespace, pod)) * on (namespace) group_left(label_radix_app) kube_namespace_labels {namespace=~\"$Radixapp.*\"}",
     "legendFormat": "Utilise {{ namespace }} - {{ workload }} - {{ pod }}"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests {resource=\"cpu\"} * on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$Namespace\"}\n) by (workload, workload_type, namespace, pod)) * on (namespace) group_left(label_radix_app) kube_namespace_labels {namespace=~\"$Radixapp.*\"}",
     "legendFormat": "Requested {{ namespace }} - {{ workload }} - {{ pod }}"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(\n    container_memory_working_set_bytes{namespace=~\"$Namespace\", container!=\"\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$Namespace\"}\n) by (workload, workload_type, namespace, pod)) * on (namespace) group_left(label_radix_app) kube_namespace_labels {namespace=~\"$Radixapp.*\"}",
     "legendFormat": "Utilise {{namespace}} - {{workload}} - {{pod}}"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests {resource=\"memory\"} * on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$Namespace\"}\n) by (workload, workload_type, namespace, pod)) * on (namespace) group_left(label_radix_app) kube_namespace_labels {namespace=~\"$Radixapp.*\"}",
     "legendFormat": "Requested {{namespace}} - {{workload}} - {{pod}}"
    }
   ]
  },
  {
   "title": "CI Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(ceil(rate(radix_operator_radix_job_processed{application=\"$Radixapp\"}[2m]))) by (status)",
     "legendFormat": "{{status}} jobs"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase {phase=\"Running\", namespace=~\"$Namespace\"} * on (namespace) group_left(label_radix_app) kube_namespace_labels {namespace=~\"$Radixapp.*\"}) by (namespace)",
     "legendFormat": "Running pods in {{namespace}}"
    },
    {
     "expr": "sum(kube_pod_status_phase {phase=\"Pending\", namespace=~\"$Namespace\"} * on (namespace) group_left(label_radix_app) kube_namespace_labels {namespace=~\"$Radixapp.*\"}) by (namespace)",
     "legendFormat": "Pending pods in {{namespace}}"
    },
    {
     "expr": "sum(kube_pod_status_phase {phase=\"Failed\", namespace=~\"$Namespace\"} * on (namespace) group_left(label_radix_app) kube_namespace_labels {namespace=~\"$Radixapp.*\"}) by (namespace)",
     "legendFormat": "Failed pods in {{namespace}}"
    }
   ]
  }
 ]
}